### ISSUE TITLE
Output images are inverted

### ISSUE THREAD

**Issue by frankinspace** [podaac/net2cog#7]
The output images produced by net2cog currently are flipped vertically. Should update so that images are orientated correctly.

**Comment by autydp** [comment]
I have a "Fix” for the inversion “problem”, however…
 - This may not be a problem - data geolocation is ok.
    - Data is Lower-Left oriented.
    - Typical TIFF viewers assume Upper-Left orientation.
    - GIS viewers will show the data correctly.

My current fix is not conditional and probably should be.
  - Only if Lat units is degrees, and increment is positive?
  
In fact, the code already had the implementation to invert the data, but it was commented out.  So the quick fix is to remove the comment markers.

**Comment by frankinspace** [comment]
Ok, I was suspecting this might be the case. If the metadata is correct and it's just a matter of the viewing software not using the metadata correctly I agree this is a non-issue.
